/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class byrne_fractal_NativeLib */

#ifndef _Included_byrne_fractal_NativeLib
#define _Included_byrne_fractal_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     byrne_fractal_NativeLib
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_byrne_fractal_NativeLib_getHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
